import Undertaker from 'undertaker';
import vfs from 'vinyl-fs';
import * as fs from "fs";
import watch from 'glob-watcher';
import type { Globs, WatchOptions } from "gulp";
export class Gulp extends Undertaker {
    src = vfs.src;
    dest = vfs.dest;
    symlink = vfs.symlink;
    Gulp: typeof Gulp | undefined;

    constructor() {
        super();
        // Bind the functions for destructuring
        this.watch = this.watch.bind(this);
        this.task = this.task.bind(this);
        this.series = this.series.bind(this);
        this.parallel = this.parallel.bind(this);
        this.registry = this.registry.bind(this);
        this.tree = this.tree.bind(this);
        this.lastRun = this.lastRun.bind(this);
        this.src = this.src.bind(this);
        this.dest = this.dest.bind(this);
        this.symlink = this.symlink.bind(this);
    }

    watch(globs: Globs, fn?: Undertaker.TaskFunction): fs.FSWatcher;

    watch(globs: Globs, opts?: WatchOptions, fn?: Undertaker.TaskFunction): fs.FSWatcher;

    watch(glob: Globs, opt?: Undertaker.TaskFunction | WatchOptions, task?: Undertaker.TaskFunction) {
        if (typeof opt === 'string' || typeof task === 'string' ||
            Array.isArray(opt) || Array.isArray(task)) {
            throw new Error('watching ' + glob + ': watch task has to be ' +
                'a function (optionally generated by using gulp.parallel ' +
                'or gulp.series)');
        }

        if (typeof opt === 'function') {
            task = opt;
            opt = {};
        }

        opt = opt || {};

        let fn;
        if (typeof task === 'function') {
            fn = this.parallel(task);
        }

        return watch(glob, opt, fn);
    };

}

// Let people use this class from our instance
Gulp.prototype.Gulp = Gulp;

const gulp = new Gulp();
export const on = gulp.on;
export const series = gulp.series;
export const task = gulp.task;
export const parallel = gulp.parallel;
export const registry = gulp.registry;
export const tree = gulp.tree;
export const lastRun = gulp.lastRun;
export default gulp